removed internal mysql server

diff --git a/assets/init b/assets/init
--- a/assets/init
+++ b/assets/init
@@ -153,15 +153,24 @@ fi
 DB_USER=${DB_USER:-root}
 DB_NAME=${DB_NAME:-gitlabhq_production}
 
-# fallback to using the internal mysql server
-DB_TYPE=${DB_TYPE:-mysql}
-DB_HOST=${DB_HOST:-localhost}
+if [ -z "${DB_HOST}" ]; then
+  echo "ERROR: "
+  echo "  Please configure the database connection."
+  echo "  Refer http://git.io/wkYhyA for more information."
+  echo "  Cannot continue without a database. Aborting..."
+  exit 1
+fi
 
 # use default port number if it is still not set
 case "${DB_TYPE}" in
   mysql) DB_PORT=${DB_PORT:-3306} ;;
   postgres) DB_PORT=${DB_PORT:-5432} ;;
-  *) echo "Unsupported database adapter. Available adapters are mysql and postgres." && exit 1 ;;
+  *)
+    echo "ERROR: "
+    echo "  Please specify the database type in use via the DB_TYPE configuration option."
+    echo "  Accepted values are \"postgres\" or \"mysql\". Aborting..."
+    exit 1
+    ;;
 esac
 
 ##
@@ -285,43 +294,6 @@ if [ -f "${SSL_CERTIFICATE_PATH}" -o -f "${CA_CERTIFICATES_PATH}" ]; then
   [ -f "${SSL_CERTIFICATE_PATH}" ] && cp "${SSL_CERTIFICATE_PATH}" /usr/local/share/ca-certificates/gitlab.crt
   [ -f "${CA_CERTIFICATES_PATH}" ] && cp "${CA_CERTIFICATES_PATH}" /usr/local/share/ca-certificates/ca.crt
   update-ca-certificates --fresh >/dev/null 2>&1
-fi
-
-# start mysql server if ${DB_HOST} is localhost
-if [ "${DB_HOST}" == "localhost" ]; then
-  if [ "${DB_TYPE}" == "postgres" ]; then
-    echo "DB_TYPE 'postgres' is not supported internally. Please provide DB_HOST."
-    exit 1
-  fi
-
-  # fix permissions and ownership of /var/lib/mysql
-  chown -R mysql:mysql /var/lib/mysql
-  chmod 700 /var/lib/mysql
-
-  # initialize MySQL data directory
-  if [ ! -d /var/lib/mysql/mysql ]; then
-    mysql_install_db --user=mysql
-  fi
-
-  echo "Starting mysql server..."
-  supervisorctl start mysqld >/dev/null
-
-  # wait for mysql server to start (max 120 seconds)
-  timeout=120
-  while ! mysqladmin -h ${DB_HOST} -u ${DB_USER} ${DB_PASS:+-p$DB_PASS} status >/dev/null 2>&1
-  do
-    timeout=$(expr $timeout - 1)
-    if [ $timeout -eq 0 ]; then
-      echo "Failed to start mysql server"
-      exit 1
-    fi
-    sleep 1
-  done
-
-  if ! mysql -h ${DB_HOST} -u ${DB_USER} ${DB_PASS:+-p$DB_PASS} -e "USE ${DB_NAME};" >/dev/null 2>&1; then
-    mysql -h ${DB_HOST} -u ${DB_USER} ${DB_PASS:+-p$DB_PASS} -e "CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` DEFAULT CHARACTER SET \`utf8\` COLLATE \`utf8_unicode_ci\`;"
-    mysql -h ${DB_HOST} -u ${DB_USER} ${DB_PASS:+-p$DB_PASS} -e "GRANT SELECT, LOCK TABLES, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER ON \`${DB_NAME}\`.* TO 'root'@'localhost';"
-  fi
 fi
 
 # configure git for the 'git' user
@@ -693,8 +665,6 @@ appStop() {
   supervisorctl stop sshd >/dev/null
   echo "Stopping nginx..."
   supervisorctl stop nginx >/dev/null
-  echo "Stopping mysqld..."
-  supervisorctl stop mysqld >/dev/null
   echo "Stopping supervisord..."
   kill -15 $(cat /var/run/supervisord.pid)
   exit
